name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Formatting
      working-directory: ./tagent
      run: cargo fmt --check --verbose
    - name: Clippy
      working-directory: ./tagent
      run: cargo clippy --no-deps
    - name: Build
      working-directory: ./tagent
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./tagent
      run: cargo test --verbose -- --test-threads=1
