name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: ./tagent
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./tagent
      run: cargo test --verbose -- --test-threads=1
